// This file is not auto generated, but should be treated as such, since it interops with unmananged code 
// and thus normal style rules don't apply.
// <auto-generated/>

namespace GW2NET.ChatLinks.Interop
{
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Explicit)]
    public struct Map
    {
        [FieldOffset(0)]
        public int pointOfInterestId;
    }
}