// This file is not auto generated, but should be treated as such, since it interops with unmananged code 
// and thus normal style rules don't apply.
// <auto-generated/>

namespace GW2NET.ChatLinks.Interop
{
    using System;
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential)]
    public struct UInt24
    {
#pragma warning disable CS3001 // Argument type is not CLS-compliant
        public UInt24(uint value)
#pragma warning restore CS3001 // Argument type is not CLS-compliant
        {
            var b = BitConverter.GetBytes(value);
            this._b0 = b[0];
            this._b1 = b[1];
            this._b2 = b[2];
        }

        private readonly byte _b0;

        private readonly byte _b1;

        private readonly byte _b2;

#pragma warning disable CS3003 // Type is not CLS-compliant
        public uint Value
#pragma warning restore CS3003 // Type is not CLS-compliant
        {
            get
            {
                return (uint)(this._b0 | (this._b1 << 8) | (this._b2 << 16));
            }
        }
    }
}